#include "rdc/Assets.h"
#include <QFile>
#include <QtTest>
#include <bit>
#include <cmath>
#include <cstdlib>
#include <limits>
extern "C" void *__cdecl RENDERDOC_AllocArrayMem(uint64_t size) { return std::malloc(size_t(size)); }
extern "C" void __cdecl RENDERDOC_FreeArrayMem(void *p) { std::free(p); }
using namespace flora;
using Json = nlohmann::json;
namespace {
ResourceId resource(uint64_t value) { return std::bit_cast<ResourceId>(value); }
Json annotationProbe() {
    Json result = Json::array();
    for (uint64_t bits : {uint64_t(0), uint64_t(123), uint64_t(255), uint64_t(0x7ff0000000000000),
                          uint64_t(0xfff0000000000000), uint64_t(0x7ff8000000000000),
                          uint64_t(0x8000000000000000), UINT64_MAX}) {
        SDObject object("probe"_lit, "uint64_t"_lit);
        object.type.basetype = SDBasic::UnsignedInteger;
        object.data.basic.u = bits;
        ResourceDescription r;
        r.annotations = &object;
        result.push_back(rdcResourceDescription(r).at("annotations"));
    }
    return result;
}
} // namespace
class RdcAssetTests : public QObject {
    Q_OBJECT
  private slots:
    void resourceGraphAndWideValues() {
        ResourceDescription r;
        r.resourceId = resource(UINT64_MAX);
        r.name = "GPA resource 25 (texture)";
        r.autogeneratedName = false;
        r.parentResources = {resource(2), resource(3)};
        r.derivedResources = {resource(4)};
        r.initialisationChunks = {5, UINT32_MAX};
        const auto j = rdcResourceDescription(r);
        QCOMPARE(j.at("resourceId"), Json("ResourceId::18446744073709551615"));
        QCOMPARE(j.at("parentResources"), Json({"ResourceId::2", "ResourceId::3"}));
        QCOMPARE(j.at("initialisationChunks"), Json({5, UINT32_MAX}));
        QVERIFY(j.at("annotations").is_null());
        QCOMPARE(j.size(), size_t(8));
        BufferDescription b;
        b.resourceId = resource(99);
        b.length = UINT64_MAX;
        b.gpuAddress = uint64_t(9007199254740993);
        const auto buffer = rdcBufferDescription(b);
        QCOMPARE(buffer.at("length").dump(), std::string("18446744073709551615"));
        QCOMPARE(buffer.at("gpuAddress").dump(), std::string("9007199254740993"));
        QCOMPARE(buffer.size(), size_t(4));
    }
    void textureMetadata() {
        TextureDescription t{};
        t.resourceId = resource(10);
        t.dimension = 3;
        t.type = TextureType::Texture3D;
        t.width = 16;
        t.height = 8;
        t.depth = 4;
        t.mips = 3;
        t.arraysize = 1;
        t.msSamp = 1;
        t.byteSize = UINT64_MAX;
        t.format.type = ResourceFormatType::Regular;
        t.format.compType = CompType::UNormSRGB;
        t.format.compCount = 4;
        t.format.compByteWidth = 1;
        t.format.SetBGRAOrder(true);
        const auto result = rdcTextureDescription(t);
        QCOMPARE(result.size(), size_t(14));
        QCOMPARE(result.at("depth"), Json(4));
        QCOMPARE(result.at("byteSize").get<uint64_t>(), UINT64_MAX);
        QCOMPARE(result.at("format").size(), size_t(4));
        QVERIFY(!result.at("format").contains("flags"));
        QCOMPARE(result.at("format").at("compType"), Json(uint32_t(CompType::UNormSRGB)));
    }
    void annotationUnion() {
        auto rows = annotationProbe();
        QCOMPARE(rows.at(1).at("data").at("basic").at("c"), Json("{"));
        QCOMPARE(rows.at(1).at("data").at("basic").at("id"), Json("ResourceId::123"));
        QCOMPARE(rows.at(3).at("data").at("basic").at("d"), Json("inf"));
        QCOMPARE(rows.at(4).at("data").at("basic").at("d"), Json("-inf"));
        QCOMPARE(rows.at(5).at("data").at("basic").at("d"), Json("nan"));
        QVERIFY(std::signbit(rows.at(6).at("data").at("basic").at("d").get<double>()));
        QCOMPARE(rows.at(7).at("data").at("basic").at("i"), Json(-1));
        QVERIFY(rdcInventoryText(rows).find("\\udcff") != std::string::npos);
    }
};
int main(int argc, char **argv) {
    QCoreApplication app(argc, argv);
    if (app.arguments().size() == 3 && app.arguments()[1] == "--probe") {
        QFile f(app.arguments()[2]);
        const auto data = rdcInventoryText(annotationProbe());
        return f.open(QIODevice::WriteOnly) &&
                       f.write(data.data(), qint64(data.size())) == qint64(data.size())
                   ? 0
                   : 1;
    }
    RdcAssetTests tests;
    return QTest::qExec(&tests, argc, argv);
}
#include "RdcAssetTests.moc"
