#include "Assets.h"
#include <cmath>
#include <cstring>
namespace flora {
namespace {
using Json = nlohmann::json;
template <typename T> std::string text(const T &value) { return std::string(value.c_str(), value.size()); }
std::string resource(ResourceId value) {
    uint64_t id{};
    static_assert(sizeof(id) == sizeof(value));
    std::memcpy(&id, &value, sizeof(id));
    return "ResourceId::" + std::to_string(id);
}
Json real(double value) {
    if (std::isfinite(value))
        return value;
    return std::isnan(value) ? "nan" : value < 0 ? "-inf" : "inf";
}
Json annotation(const SDObject *value) {
    if (!value)
        return nullptr;
    // The original plain() adapter serializes the exposed union views, not
    // children (which the Python API exposes only through callable methods).
    const auto &bits = value->data.basic;
    uint64_t u{};
    int64_t i{};
    double d{};
    unsigned char c{};
    std::memcpy(&u, &bits, sizeof(u));
    std::memcpy(&i, &bits, sizeof(i));
    std::memcpy(&d, &bits, sizeof(d));
    std::memcpy(&c, &bits, sizeof(c));
    return {{"name", text(value->name)},
            {"type",
             {{"name", text(value->type.name)},
              {"basetype", uint32_t(value->type.basetype)},
              {"byteSize", value->type.byteSize},
              {"flags", uint32_t(value->type.flags)}}},
            {"data",
             {{"string", text(value->data.str)},
              {"basic",
               {{"u", u},
                {"i", i},
                {"d", real(d)},
                {"b", c != 0},
                {"c", std::string(1, char(c))},
                {"id", "ResourceId::" + std::to_string(u)}}}}}};
}
} // namespace
nlohmann::json rdcResourceFormat(const ResourceFormat &format) {
    // Private format flags are not properties of the original Python adapter.
    return {{"type", uint32_t(format.type)},
            {"compType", uint32_t(format.compType)},
            {"compCount", format.compCount},
            {"compByteWidth", format.compByteWidth}};
}
nlohmann::json rdcResourceDescription(const ResourceDescription &r) {
    Json parents = Json::array(), derived = Json::array(), chunks = Json::array();
    for (auto id : r.parentResources)
        parents.push_back(resource(id));
    for (auto id : r.derivedResources)
        derived.push_back(resource(id));
    for (auto index : r.initialisationChunks)
        chunks.push_back(index);
    return {{"resourceId", resource(r.resourceId)},
            {"type", uint32_t(r.type)},
            {"autogeneratedName", r.autogeneratedName},
            {"name", text(r.name)},
            {"initialisationChunks", chunks},
            {"derivedResources", derived},
            {"parentResources", parents},
            {"annotations", annotation(r.annotations)}};
}
nlohmann::json rdcTextureDescription(const TextureDescription &t) {
    return {{"resourceId", resource(t.resourceId)},
            {"format", rdcResourceFormat(t.format)},
            {"dimension", t.dimension},
            {"type", uint32_t(t.type)},
            {"width", t.width},
            {"height", t.height},
            {"depth", t.depth},
            {"cubemap", t.cubemap},
            {"mips", t.mips},
            {"arraysize", t.arraysize},
            {"creationFlags", uint32_t(t.creationFlags)},
            {"msQual", t.msQual},
            {"msSamp", t.msSamp},
            {"byteSize", t.byteSize}};
}
nlohmann::json rdcBufferDescription(const BufferDescription &b) {
    return {{"resourceId", resource(b.resourceId)},
            {"creationFlags", uint32_t(b.creationFlags)},
            {"gpuAddress", b.gpuAddress},
            {"length", b.length}};
}
std::string rdcInventoryText(const nlohmann::json &value) {
    if (value.is_string()) {
        const auto &s = value.get_ref<const std::string &>();
        if (s.size() == 1 && static_cast<unsigned char>(s[0]) >= 0x80) {
            constexpr char hex[] = "0123456789abcdef";
            const auto byte = static_cast<unsigned char>(s[0]);
            return std::string("\"\\udc") + hex[byte >> 4] + hex[byte & 15] + '"';
        }
    }
    if (!value.is_array() && !value.is_object())
        return value.dump();
    std::string result = value.is_array() ? "[" : "{";
    bool first = true;
    for (const auto &item : value.items()) {
        if (!first)
            result += ',';
        first = false;
        if (value.is_object())
            result += Json(item.key()).dump() + ':';
        result += rdcInventoryText(item.value());
    }
    return result + (value.is_array() ? ']' : '}');
}
} // namespace flora
