"""Generate the captured-path casefold table from the reference Python Unicode database.

Development only. Pin the Unicode version so regeneration cannot silently change
the filename equality used by the recovered Python implementation.
"""
from pathlib import Path
import unicodedata

assert unicodedata.unidata_version == '15.1.0', unicodedata.unidata_version
entries, data = [], []
for cp in range(0x110000):
    folded = chr(cp).casefold()
    if folded != chr(cp):
        entries.append((cp, len(data), len(folded)))
        data.extend(map(ord, folded))
lines = ['#pragma once', '// Generated by tools/generate_unicode_casefold.py; Unicode 15.1.0.',
         '// Full, locale-independent case folding for captured Python-compatible paths.',
         '#include <cstdint>', 'namespace flora::shader_debug {',
         'struct CaseFoldEntry { uint32_t codepoint; uint16_t offset; uint8_t size; };',
         'inline constexpr CaseFoldEntry caseFoldEntries[] = {']
lines += ['    {0x%x, %d, %d},' % row for row in entries]
lines += ['};', 'inline constexpr char32_t caseFoldData[] = {']
lines += ['    '+', '.join('0x%x' % c for c in data[i:i+16])+',' for i in range(0, len(data), 16)]
lines += ['};', '} // namespace flora::shader_debug', '']
target = Path(__file__).resolve().parents[1]/'src/application/UnicodeCaseFoldData.h'
target.write_text('\n'.join(lines), encoding='utf-8')
print(len(entries), 'mappings;', len(data), 'codepoints;', target)
